// examples/react/src/App.tsx
import { useEffect, useState } from "react";
import type { ExampleUser } from "../../shared/src";
import { useBrass } from "./brass";

export function App() {
  const brass = useBrass();
  const [user, setUser] = useState<ExampleUser | undefined>();
  const [error, setError] = useState<string | undefined>();

  useEffect(() => {
    let alive = true;

    brass.getUser("42")
      .then((nextUser) => {
        if (alive) setUser(nextUser);
      })
      .catch((nextError) => {
        if (alive) setError(nextError instanceof Error ? nextError.message : String(nextError));
      });

    return () => {
      alive = false;
    };
  }, [brass]);

  return (
    <main>
      <h1>Brass React example</h1>
      <p>React context owns the Brass HTTP client, runtime, and observability instance.</p>
      {error ? <pre>{error}</pre> : <pre>{JSON.stringify(user ?? { loading: true }, null, 2)}</pre>}
      <button type="button" onClick={() => void brass.getUser("1").then(setUser)}>
        Load admin user
      </button>
    </main>
  );
}

// examples/angular/src/app/app.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnDestroy, OnInit, inject } from "@angular/core";
import type { ExampleUser } from "../../../shared/src";
import { BRASS } from "./brass.providers";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [CommonModule],
  template: `
    <main>
      <h1>Brass Angular example</h1>
      <p>Angular injects Brass with an InjectionToken provider.</p>

      <pre *ngIf="user; else loading">{{ user | json }}</pre>
      <ng-template #loading>
        <pre>{{ error || "loading" }}</pre>
      </ng-template>

      <button type="button" (click)="loadAdmin()">Load admin user</button>
    </main>
  `,
})
export class AppComponent implements OnInit, OnDestroy {
  private readonly brass = inject(BRASS);

  user?: ExampleUser;
  error?: string;

  async ngOnInit() {
    await this.loadUser("42");
  }

  ngOnDestroy() {
    void this.brass.shutdown();
  }

  async loadAdmin() {
    await this.loadUser("1");
  }

  private async loadUser(id: string) {
    try {
      this.error = undefined;
      this.user = await this.brass.getUser(id);
    } catch (error) {
      this.error = error instanceof Error ? error.message : String(error);
    }
  }
}
